version: "3"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=IPN
    ports: 
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on: 
      - postgres 



# postgres:
#   image: postgres:9.4
#   volumes:
#     - ./init.sql:/docker-entrypoint-initdb.d/init.sql